name: automated test
on: [push, pull_request]
jobs:
  math-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [18.x, 20.x, 22.x]
            distribution: ['ubuntu:latest', 'centos:latest', 'debian:latest']
    container: ${{matrix.distribution}}
    steps:
      - run: echo "checking os info..."
      - run: cat /etc/*-release
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
